services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis
